### ISSUE TITLE
problem adding the delete code

### ISSUE THREAD

**Issue by hakankk** [fourtonfish/random-image-twitterbot#1]
New to this progamming and I couldn't place the code for deleting. Can anyone help?

fs.unlink(image_path, function(err){
  if (err){
    console.log('ERROR: unable to delete image ' + image_path);
  }
  else{
    console.log('image ' + image_path + ' was deleted');
  }
}

**Comment by stefanbohacek** [comment]
@hakankk Check out https://github.com/fourtonfish/random-image-twitterbot/blob/master/server-delete-images.js.
