### ISSUE TITLE
general message for each picture or unique message for each picture

### ISSUE THREAD

**Issue by hakankk** [fourtonfish/random-image-twitterbot#2]
Hi 

I tried to insert T.post('statuses/update', { status: 'Look, I am tweeting!' } so that there could be a fixed message tweeted with each picture. I tried several combinations but it didn't work.

In one occasion it tweets the message in one tweet and tweets the picture in another.

It would actually be great if it would be possible to pull dedicated message for each picture. I saw a very close version but I couldn't make the Python and its code work.

It would be great if anyone can help.

Thank you
Best

**Comment by stefanbohacek** [comment]
@hakankk Hi, please check out the updated `server.js` script. This seems to be working for me:

https://github.com/fourtonfish/random-image-twitterbot/blob/master/server.js#L28

Check out https://twitter.com/eddbott
